# Используем официальный образ Python
FROM python:3.11-slim

# Устанавливаем рабочую директорию внутри контейнера
WORKDIR /app

# Копируем файл с зависимостями и устанавливаем их
# Это делается отдельно для эффективного кэширования слоёв Docker
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
RUN apt-get update && apt-get install -y iputils-ping && rm -rf /var/lib/apt/lists/*


# Копируем весь код приложения
COPY . .

# Открываем порт, который будет слушать приложение
EXPOSE 8000

# Команда для запуска приложения через uvicorn
# --reload обычно используется для разработки, для продакшена лучше использовать gunicorn
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]