server {
    listen 80;
    server_name goalmanager.work.gd; # Замените на ваш домен или IP

    # Отдаём статические файлы фронтенда
    location / {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /index.html; # Для корректной работы роутинга в SPA
    }

    # Проксируем все запросы, начинающиеся с /api/, на наш бэкенд
    location /api/ {
        proxy_pass http://api:8000/; # Убираем /api/ при передаче запроса
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}